# -*- coding: utf-8 -*-
"""bala codinggg

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1igvPHLl_H4d2GLL6d-KwYYFPrRuh8FAc
"""

import pandas as pd
df= pd.read_csv("/content/drive/MyDrive/python files/final dataset.csv")

df.head(10)
#shows top 10 rows

df.drop('title', axis=1, inplace = True)
df.drop('weight', axis=1, inplace = True)
#deleted the column title and weight

df.head(5)

df.info()
#shows the dataset deets

df.columns
#shows column name

df.shape
#how many rows n columns

df.tail()
#shows bottom rows

print(df.isnull().sum())
#shows missing values

df['new_price'] = pd.to_numeric(df['new_price'], errors='coerce')
df['old_price'] = pd.to_numeric(df['old_price'], errors='coerce')
df['discount'] = pd.to_numeric(df['discount'], errors='coerce')
df['shades'] = pd.to_numeric(df['shades'], errors='coerce')
df['rating_count'] = pd.to_numeric(df['rating_count'], errors='coerce')
df['review_count'] = pd.to_numeric(df['review_count'], errors='coerce')
df['weight_ml'] = pd.to_numeric(df['weight_ml'], errors='coerce')
df['weight_g'] = pd.to_numeric(df['weight_g'], errors='coerce')
df['rating'] = pd.to_numeric(df['rating'], errors='coerce')
#converting every column to the correct one

df.info()
#check deets of data

df['discount'] = df['discount'].fillna(
    (df['old_price'] - df['new_price']) / df['old_price'])
#fills missing discount using the formula discount = (old - new) / old.

df['new_price'] = df['new_price'].fillna(
    df['old_price'] * (1 - df['discount']))
#using math it fills new price

df['old_price'] = df['old_price'].fillna(
    df['new_price'] / (1 - df['discount']))
##using math it fills old price

df.isnull().sum()
#checks missing values

df.info()

df.head(5)

df.info()

df["rating_count"] = df["rating_count"].fillna(0).astype(int)
df["review_count"] = df["review_count"].fillna(0).astype(int)
#fills missing rating_count with 0

df.head(5)

df.isnull().sum()

df.tail()

df.isnull().sum()

df["item"] = df["item"].fillna("unknown")
#fills missing values with the text "unknown".

df["subitem"] = df["subitem"].fillna("unknown")
#fills missing values with the text "unknown".

df["rating"] = df["rating"].fillna("no_rating")
#fills missing values with the text "unknown".

df.isnull().sum()

mask = df["old_price"].isna() & df["new_price"].notna() & df["discount"].notna() & (1 - df["discount"] != 0)
df.loc[mask, "old_price"] = df.loc[mask, "new_price"] / (1 - df.loc[mask, "discount"])
#fixing the math for old price new disc

mask = df["discount"].isna() & df["old_price"].notna() & df["new_price"].notna() & (df["old_price"] > 0)
df.loc[mask, "discount"] = (df.loc[mask, "old_price"] - df.loc[mask, "new_price"]) / df.loc[mask, "old_price"]
#fixing the math for old price new disc

df.isnull().sum()

df["shades"] = df["shades"].fillna("null")
#fills missing shades with the text "null"

df.isnull().sum()

df.info()

print(df.duplicated().sum())
#check duplicates

df = df.drop_duplicates()
#drop duplicates

print(df.duplicated().sum())
#check duplicates

import seaborn as sns
import matplotlib.pyplot as plt

numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns
#checking for outliers

plt.figure(figsize=(15, 10))
for i, col in enumerate(numerical_cols, 1):
    plt.subplot(3, 3, i)  # Adjust subplot grid as needed
    sns.boxplot(x=df[col])
    plt.title(f'Boxplot of {col}')
plt.tight_layout()
plt.show()

# histogram of new price distribution
x = df["new_price"].dropna()

plt.figure(figsize=(8,5))
plt.hist(x, bins=50)
plt.title("Distribution of New Price")
plt.xlabel("New Price")
plt.ylabel("Count")
plt.tight_layout()
plt.show()

# discount distribution
x = df["discount"].dropna()

plt.figure(figsize=(8,5))
plt.hist(x, bins=40)
plt.title("Distribution of Discount")
plt.xlabel("Discount (fraction)")
plt.ylabel("Count")
plt.tight_layout()
plt.show()

df['rating'] = pd.to_numeric(df['rating'], errors='coerce')

# rating distribution
x = df["rating"].dropna()

plt.figure(figsize=(8,5))
plt.hist(x, bins=20)
plt.title("Distribution of Ratings")
plt.xlabel("Rating")
plt.ylabel("Count")
plt.tight_layout()
plt.show()

#top brands (market coverage) top 15 brands by number of products
top = df["brand"].value_counts().head(15)

plt.figure(figsize=(10,5))
plt.bar(top.index, top.values)
plt.xticks(rotation=45, ha="right")
plt.title("Top 15 Brands by Number of Products")
plt.ylabel("Product count")
plt.tight_layout()
plt.show()

#top brands by average rating (with minimum volume filter)
brand_stats = df.groupby("brand").agg(
    avg_rating=("rating","mean"),
    n_products=("brand","size"),
    total_reviews=("review_count","sum")
).dropna(subset=["avg_rating"])

filtered = brand_stats[brand_stats["n_products"] >= 30].sort_values("avg_rating", ascending=False).head(15)

plt.figure(figsize=(10,5))
plt.bar(filtered.index, filtered["avg_rating"].values)
plt.xticks(rotation=45, ha="right")
plt.title("Top Brands by Avg Rating (min 30 products)")
plt.ylabel("Average rating")
plt.tight_layout()
plt.show()

#category mix (what your catalog looks like) a) items share (bar)
item_counts = df["item"].value_counts().head(12)

plt.figure(figsize=(9,5))
plt.bar(item_counts.index, item_counts.values)
plt.xticks(rotation=45, ha="right")
plt.title("Top Items by Product Count")
plt.ylabel("Count")
plt.tight_layout()
plt.show()

#item x subitem heatmap (composition)
pivot = pd.pivot_table(df, index="item", columns="subitem", values="brand", aggfunc="count", fill_value=0)

plt.figure(figsize=(15,20))
plt.imshow(pivot.values, aspect="auto")
plt.xticks(range(len(pivot.columns)), pivot.columns, rotation=90)
plt.yticks(range(len(pivot.index)), pivot.index)
plt.title("Item vs Subitem: Product Counts")
plt.colorbar(label="Count")
plt.tight_layout()
plt.show()

#price comparison by category (business insight) a) average new price by item
avg_price_item = df.groupby("item")["new_price"].mean().sort_values(ascending=False).head(12)

plt.figure(figsize=(10,5))
plt.bar(avg_price_item.index, avg_price_item.values)
plt.xticks(rotation=45, ha="right")
plt.title("Average New Price by Item (Top 12)")
plt.ylabel("Avg new price")
plt.tight_layout()
plt.show()

import numpy as np

#old vs new price (avg) by item (shows discount strategy)
g = df.groupby("item")[["old_price","new_price"]].mean().dropna().sort_values("old_price", ascending=False).head(10)

x = np.arange(len(g.index))
w = 0.4

plt.figure(figsize=(10,5))
plt.bar(x - w/2, g["old_price"].values, width=w, label="Avg old price")
plt.bar(x + w/2, g["new_price"].values, width=w, label="Avg new price")
plt.xticks(x, g.index, rotation=45, ha="right")
plt.title("Average Old vs New Price by Item")
plt.legend()
plt.tight_layout()
plt.show()

#discount analysis (promotions, strategy) a) average discount by item
avg_disc = df.groupby("item")["discount"].mean().dropna().sort_values(ascending=False).head(12)

plt.figure(figsize=(10,5))
plt.bar(avg_disc.index, avg_disc.values)
plt.xticks(rotation=45, ha="right")
plt.title("Average Discount by Item (Top 12)")
plt.ylabel("Avg discount")
plt.tight_layout()
plt.show()

#discount vs new price (scatter)
tmp = df[["discount","new_price"]].dropna().sample(min(3000, len(df.dropna(subset=["discount","new_price"]))), random_state=1)

plt.figure(figsize=(7,5))
plt.scatter(tmp["discount"], tmp["new_price"], s=10)
plt.title("Discount vs New Price (sample)")
plt.xlabel("Discount")
plt.ylabel("New price")
plt.tight_layout()
plt.show()

#rating drivers (what links to better ratings)a) price vs rating (scatter)
tmp = df[["new_price","rating"]].dropna()
tmp = tmp.sample(min(4000, len(tmp)), random_state=1)

plt.figure(figsize=(7,5))
plt.scatter(tmp["new_price"], tmp["rating"], s=10)
plt.title("New Price vs Rating (sample)")
plt.xlabel("New price")
plt.ylabel("Rating")
plt.tight_layout()
plt.show()

#rating vs review volume (log scale)
tmp = df[["rating","review_count"]].dropna()
tmp = tmp.sample(min(4000, len(tmp)), random_state=1)

plt.figure(figsize=(7,5))
plt.scatter(tmp["review_count"], tmp["rating"], s=10)
plt.xscale("log")
plt.title("Review Count vs Rating (log scale)")
plt.xlabel("Review count (log)")
plt.ylabel("Rating")
plt.tight_layout()
plt.show()

#bubble chart: price vs rating, bubble size = rating_count
tmp = df[["new_price","rating","rating_count"]].dropna()
tmp = tmp.sample(min(3000, len(tmp)), random_state=1)

sizes = np.clip(tmp["rating_count"], 1, np.percentile(tmp["rating_count"], 90))
plt.figure(figsize=(7,5))
plt.scatter(tmp["new_price"], tmp["rating"], s=sizes, alpha=0.4)
plt.title("Price vs Rating (bubble size = rating_count)")
plt.xlabel("New price")
plt.ylabel("Rating")
plt.tight_layout()
plt.show()

#correlation heatmap (classic analytics slide)
num = df.select_dtypes(include=["int64","float64"]).copy()
corr = num.corr(numeric_only=True)

plt.figure(figsize=(9,7))
plt.imshow(corr.values, aspect="auto")
plt.xticks(range(len(corr.columns)), corr.columns, rotation=90)
plt.yticks(range(len(corr.index)), corr.index)
plt.title("Correlation Heatmap (Numeric Features)")
plt.colorbar()
plt.tight_layout()
plt.show()

#“top products” style charts (stakeholder-friendly) a) top 10 products by review_count
top_prod = df.sort_values("review_count", ascending=False).head(10)[["product name","brand","review_count","rating","new_price"]]

plt.figure(figsize=(10,5))
plt.barh(top_prod["product name"], top_prod["review_count"])
plt.gca().invert_yaxis()
plt.title("Top 10 Products by Review Count")
plt.xlabel("Review count")
plt.tight_layout()
plt.show()

#top 10 “best value” (high rating + high discount) simple score
tmp = df[["product name","brand","rating","discount","review_count"]].copy()
tmp["rating"] = pd.to_numeric(tmp["rating"], errors="coerce")
tmp["discount"] = pd.to_numeric(tmp["discount"], errors="coerce")
tmp["review_count"] = pd.to_numeric(tmp["review_count"], errors="coerce").fillna(0)

tmp = tmp.dropna(subset=["rating","discount"])
tmp["value_score"] = tmp["rating"] * (1 + tmp["discount"]) * np.log1p(tmp["review_count"])

best = tmp.sort_values("value_score", ascending=False).head(10)

plt.figure(figsize=(10,5))
plt.barh(best["product name"], best["value_score"])
plt.gca().invert_yaxis()
plt.title("Top 10 Products by Value Score")
plt.xlabel("Value score")
plt.tight_layout()
plt.show()

#pareto chart (80/20 insight for brands)
counts = df["brand"].value_counts()
cum_pct = counts.cumsum() / counts.sum() * 100
top = counts.head(20)
top_cum = cum_pct.head(20)

fig, ax1 = plt.subplots(figsize=(10,5))
ax1.bar(top.index, top.values)
ax1.set_xticklabels(top.index, rotation=45, ha="right")
ax1.set_ylabel("Product count")
ax1.set_title("Pareto: Brand Contribution (Top 20)")

ax2 = ax1.twinx()
ax2.plot(range(len(top_cum)), top_cum.values, marker="o")
ax2.set_ylabel("Cumulative %")
ax2.set_ylim(0, 110)

plt.tight_layout()
plt.show()

#rating distribution by category (boxplot without seaborn)
cats = df["item"].value_counts().head(6).index
data = [df.loc[df["item"]==c, "rating"].dropna().values for c in cats]

plt.figure(figsize=(10,5))
plt.boxplot(data, labels=cats)
plt.xticks(rotation=45, ha="right")
plt.title("Rating Distribution by Item (Top 6)")
plt.ylabel("Rating")
plt.tight_layout()
plt.show()

#most common words in product names (simple bar)
import re
from collections import Counter

names = df["product name"].dropna().astype(str).str.lower()
tokens = []
for s in names:
    s = re.sub(r"[^a-z0-9\s]", " ", s)
    tokens += [t for t in s.split() if len(t) > 2]

common = Counter(tokens).most_common(15)
words, freqs = zip(*common)

plt.figure(figsize=(10,5))
plt.bar(words, freqs)
plt.xticks(rotation=45, ha="right")
plt.title("Most Common Words in Product Names")
plt.tight_layout()
plt.show()

#check skewness kurtosis
df.skew(numeric_only=True)
df.kurtosis(numeric_only=True)

#avg price, rating, discount by brand
brand_summary = df.groupby("brand").agg({
    "new_price":"mean",
    "rating":"mean",
    "discount":"mean",
    "review_count":"sum"
}).sort_values("review_count", ascending=False)

brand_summary.head(15)

#price segmentation (cheap vs premium market)
df["price_segment"] = pd.qcut(df["new_price"], 4, labels=["Low","Mid","High","Premium"])
df["price_segment"].value_counts()

#comparing ratings
df.groupby("price_segment")["rating"].mean()

#niche vs crowded markets
df.groupby("item")["brand"].nunique().sort_values(ascending=False)

df.info()

import numpy as np

df["success"] = np.where(
    (df["rating"] >= 4.0) & (df["review_count"] > df["review_count"].median()),
    1, 0
)

data = df
X = data.drop("success", axis=1)
y = data["success"]
print(X.shape)
print(y.shape)

df.head(5)

from sklearn.preprocessing import OneHotEncoder
import pandas as pd

def onehot_item_subitem(df):
    df = df.copy()

    cols = ["item", "subitem"]

    encoder = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
    encoded = encoder.fit_transform(df[cols])

    encoded_df = pd.DataFrame(
        encoded,
        columns=encoder.get_feature_names_out(cols),
        index=df.index
    )

    df = df.drop(columns=cols)
    df = pd.concat([df, encoded_df], axis=1)

    return df

X = onehot_item_subitem(X)
print(X.shape)
X.head()

from sklearn import model_selection
test_size = 0.20
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=test_size, random_state=7)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

import matplotlib.pyplot as plt
import pandas as pd

count_class = y_train.value_counts()
plt.bar(count_class.index, count_class.values)
plt.xlabel('Class')
plt.ylabel('Count')
plt.title('Class Distribution (AS-IS)')
plt.xticks(count_class.index, ['Class 0', 'Class 1'])
plt.show()

#IGNORE FROM HERE

from imblearn.over_sampling import ADASYN
adasyn = ADASYN(sampling_strategy='minority')
X_train_ADASYN, y_train_ADASYN = adasyn.fit_resample(X_train, y_train)
print(X_train_ADASYN.shape)
print(y_train_ADASYN.shape)
print("After ADASYN:\n", y_train_ADASYN.value_counts())

X_train.isna().sum().sort_values(ascending=False).head(20)

drop_cols = []
if "keywords" in X_train.columns:
    drop_cols.append("keywords")
if "rating" in X_train.columns:
    drop_cols.append("rating")

X_train2 = X_train.drop(columns=drop_cols, errors="ignore")
X_test2 = X_test.drop(columns=drop_cols, errors="ignore")

X_train["is_ml"] = (X_train["weight_ml"] > 0).astype(int)
X_test["is_ml"] = (X_test["weight_ml"] > 0).astype(int)

X_train.isna().sum().sort_values(ascending=False).head(20)

if "keywords" in X_train.columns:
    X_train = X_train.drop(columns=["keywords"])
    X_test = X_test.drop(columns=["keywords"])

if "weight_ml" in X_train.columns:
    X_train["is_ml"] = (X_train["weight_ml"] > 0).astype(int)
    X_test["is_ml"] = (X_test["weight_ml"] > 0).astype(int)

for col in ["discount", "old_price"]:
    if col in X_train.columns:
        med = X_train[col].median()
        X_train[col] = X_train[col].fillna(med)
        X_test[col] = X_test[col].fillna(med)

if "rating" in X_train.columns:
    X_train = X_train.drop(columns=["rating"])
    X_test = X_test.drop(columns=["rating"])

print("Total NaNs in train:", X_train.isna().sum().sum())
print("Any object columns left:", X_train.dtypes.eq("object").any())

X_train.isna().sum().sort_values(ascending=False).head(20)

for col in ["weight_ml", "weight_g"]:
    if col in X_train.columns:
        X_train[col] = X_train[col].fillna(0)
        X_test[col] = X_test[col].fillna(0)

print("Total NaNs in train:", X_train.isna().sum().sum())
print("Any object columns left:", X_train.dtypes.eq("object").any())

obj_cols = X_train.select_dtypes(include="object").columns
obj_cols

#IGNORE ENDS

from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(criterion = 'entropy', max_depth = 4)
DTree= model.fit(X_train,y_train)
y_pred = model.predict(X_test)

X_train.select_dtypes(include="object").columns

X_train = pd.get_dummies(X_train, columns=["brand"], drop_first=True)
X_test  = pd.get_dummies(X_test, columns=["brand"], drop_first=True)

# align columns
X_test = X_test.reindex(columns=X_train.columns, fill_value=0)

import pandas as pd

X_train["shades"] = pd.to_numeric(X_train["shades"], errors="coerce")
X_test["shades"]  = pd.to_numeric(X_test["shades"], errors="coerce")

med = X_train["shades"].median()
X_train["shades"] = X_train["shades"].fillna(med)
X_test["shades"]  = X_test["shades"].fillna(med)

X_train = X_train.drop(columns=["product name"], errors="ignore")
X_test  = X_test.drop(columns=["product name"], errors="ignore")

X_train.select_dtypes(include="object").columns

print("Any object left:", X_train.dtypes.eq("object").any())
print("Total NaNs:", X_train.isna().sum().sum())

X_train = X_train.drop(columns=["price_segment", "review_bucket"], errors="ignore")
X_test  = X_test.drop(columns=["price_segment", "review_bucket"], errors="ignore")

from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(criterion = 'entropy', max_depth = 4)
DTree= model.fit(X_train,y_train)
y_pred = model.predict(X_test)

cutoff = 0.9
y_pred  = (DTree.predict_proba(X_test)[:, 1] >= cutoff).astype(int)

import matplotlib.pyplot as plt
import numpy
from sklearn import metrics
from sklearn.metrics import precision_score, recall_score

confusion_matrix = metrics.confusion_matrix(y_test, y_pred)
cm_display = metrics.ConfusionMatrixDisplay(confusion_matrix = confusion_matrix, display_labels = [False, True])
cm_display.plot()
plt.show()

accuracy = metrics.accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)

print("Accuracy:", accuracy*100, "%")
print("Precision:", precision*100, "%")
print("Recall:",recall*100, "%")

from sklearn import metrics
import matplotlib.pyplot as plt
fpr, tpr, _ = metrics.roc_curve(y_test,  y_pred)
auc = metrics.roc_auc_score(y_test, y_pred)

plt.plot(fpr,tpr,label="AUC="+str(auc))
plt.ylabel('True Positive Rate')
plt.xlabel('False Positive Rate')
plt.legend(loc=4)
plt.show()

Predictors = list(X_train.columns.values)

feature_importances = pd.Series(DTree.feature_importances_, index=Predictors)
feature_importances.nlargest(10).plot(kind='barh')

numcols = list(X.columns.values)

from matplotlib import pyplot as plt
from sklearn.tree import plot_tree

target_names =y_train.unique().tolist()
target_namestxt = [str(x) for x in target_names]

fig, axes = plt.subplots(nrows = 1,ncols = 1,figsize = (30,10), dpi=500)
plot_tree(model,feature_names = X.columns[:], class_names = target_namestxt,     filled = True,      rounded = True, fontsize=9)

print("tree expects:", model.n_features_in_)
print("X has:", X.shape[1])
print("X_train has:", X_train.shape[1])

feature_names = X_train.columns.tolist()
class_names = [str(x) for x in model.classes_]  # safer than y_train.unique()

plt.figure(figsize=(30,10), dpi=500)
plot_tree(
    model,
    feature_names=feature_names,
    class_names=class_names,
    filled=True,
    rounded=True,
    fontsize=9
)
plt.show()

#checking logistic regression from tatget
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

log_model = LogisticRegression(max_iter=1000)
log_model.fit(X_train, y_train)

y_pred_log = log_model.predict(X_test)

print(classification_report(y_test, y_pred_log))

from sklearn.metrics import accuracy_score, precision_score, recall_score

acc = accuracy_score(y_test, y_pred)
prec = precision_score(y_test, y_pred)
rec = recall_score(y_test, y_pred)

print("Accuracy:", acc*100)
print("Precision:", prec*100)
print("Recall:", rec*100)

from sklearn.metrics import roc_auc_score

auc = roc_auc_score(y_test, y_pred)
print("AUC:", auc)

from sklearn.metrics import roc_curve
import matplotlib.pyplot as plt

fpr, tpr, _ = roc_curve(y_test, y_pred)

plt.plot(fpr, tpr, label="AUC="+str(round(auc,3)))
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve - Logistic Regression")
plt.legend()
plt.show()

#random forest
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

print(classification_report(y_test, y_pred_rf))

import pandas as pd
rf_importances = pd.Series(rf.feature_importances_, index=X_train.columns)
rf_importances.nlargest(10).plot(kind='barh')

#cross validation
from sklearn.model_selection import cross_val_score

scores = cross_val_score(rf, X_train, y_train, cv=5, scoring='accuracy')
print("Cross-val accuracy:", scores.mean())

#is premium segement more succesful?
df.groupby("price_segment")["success"].mean()

#Which brands convert better?
brand_success = df.groupby("brand")["success"].mean().sort_values(ascending=False)
brand_success.head(15)